### ISSUE TITLE
The configuration file describes ALWAYS and NEVER incorrectly

### ISSUE THREAD

**Issue by atakle** [UnRealDinnerbone/TrampleStopper#1]
The comments in the configuration file states that
> Never: Never trampled farmland,
> Always: It Always get trampled,

but the actual behaviour is the opposite. When the configuration is set to ALWAYS, the farmland is never tramlped, and vice versa.

**Comment by UnRealDinnerbone** [comment]
There just realized a new version on curse should be out soon
