### ISSUE TITLE
Crash on Mojang Studios load screen when it finished forge 1.19-41.0.61

### ISSUE THREAD

**Issue by ExiledMiner04** [UnRealDinnerbone/TrampleStopper#11]
The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=Block{minecraft:air}}, Reference{null=Block{minecraft:air}}]
Exit Code: -1
[crash-2022-06-28_03.14.42-client.txt](https://github.com/UnRealModding/TrampleStopper/files/8998629/crash-2022-06-28_03.14.42-client.txt)

**Comment by UnRealDinnerbone** [comment]
Should hopefully be fixed
