### ISSUE TITLE
1.19.2 server crash (during chunk generation ?)

### ISSUE THREAD

**Issue by Daltaxy** [UnRealDinnerbone/TrampleStopper#12]
Hello. I am coming from https://forums.minecraftforge.net/topic/116760-1192-server-crash-why/
Apparently the crash was due to this mod.
As I said there, I was running faster than the world generation, and as I reached the empty invisible (not loaded) chunks, the server crashed a few seconds after.
debug.log : https://gist.github.com/Daltaxy/1b6bd0b945fc2afe3bf26d65179aadb0
server log : https://paste.shockbyte.com/vubososevopijuhapiwi
Thank you.

**Comment by UnRealDinnerbone** [comment]
Fixed new build should be out soon on CurseForge
