### ISSUE TITLE
[1.18.2] Doesn't work

### ISSUE THREAD

**Issue by qznfbnj** [UnRealDinnerbone/TrampleStopper#13]
Forge-40.2.1
TrampleStopper-3.1.0-build.27+mc1.18.2

![image](https://github.com/UnRealModding/TrampleStopper/assets/100760086/57fb8223-7239-4bf5-88bd-3f08955f21dd)
![image](https://github.com/UnRealModding/TrampleStopper/assets/100760086/3a7ad32c-c689-4211-8cfc-775437ad1353)
![image](https://github.com/UnRealModding/TrampleStopper/assets/100760086/0c5d7fa9-cf7f-4841-a5b0-683c126b6076)
![image](https://github.com/UnRealModding/TrampleStopper/assets/100760086/9ef76d4d-8b8c-424b-b70c-761ad1c18712)

**Comment by UnRealDinnerbone** [comment]
Do you have any other mods insalled?

**Comment by qznfbnj** [comment]
I double checked, no other mods.
![image](https://github.com/UnRealModding/TrampleStopper/assets/100760086/22a34f21-bd53-41e6-89ee-53e119e33402)
![image](https://github.com/UnRealModding/TrampleStopper/assets/100760086/c92f28a3-1f34-4dab-b298-164a4831f6f7)
![image](https://github.com/UnRealModding/TrampleStopper/assets/100760086/d3ae39c0-aaca-491c-b1da-317f6effb58d)
![image](https://github.com/UnRealModding/TrampleStopper/assets/100760086/313c249d-b8fb-49a9-b65b-31ae1456367e)
![image](https://github.com/UnRealModding/TrampleStopper/assets/100760086/427197c5-f611-43e6-9fbe-a521bc825ea6)

**Comment by qznfbnj** [comment]
Re-download and test again, still the same
