### ISSUE TITLE
Remove Trenzalore dependency

### ISSUE THREAD

**Issue by JaisDK** [UnRealDinnerbone/TrampleStopper#14]
### Feature Description

It's not good practice to include a hidden dependency to a mod that's not really a library mod and which adds functionality that the player is not looking for when installing this mod. It just looks like a way to farm points.

**Comment by UnRealDinnerbone** [comment]
All custom tweaks add to Trenzalore were removed in latest version of 1.20.1, if you don't want them for old versions there is a config
