### ISSUE TITLE
Mobs trample framland

### ISSUE THREAD

**Issue by penturt** [UnRealDinnerbone/TrampleStopper#16]
### Minecraft Version

1.20.1

### Modloader

forge 1.20.1 - 47.2.20

### Mod version

TrampleStopper-Forge-5.0.0+mc1.20.1.jar

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

N/A

### Description of the issue you are having

i have type = "NEVER" set in the configs yet mobs are able to trample farmland.

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Please upload the log file

**Comment by penturt** [comment]
I started a new single player world went to a village and was able to trample farmland. also included config files.

[tramplestopper.json](https://github.com/nanite/TrampleStopper/files/14217114/tramplestopper.json)
[tramplestopper-common.txt](https://github.com/nanite/TrampleStopper/files/14217159/tramplestopper-common.txt) - Renamed to .txt to be able to upload
[latest.log](https://github.com/nanite/TrampleStopper/files/14217142/latest.log)

**Comment by penturt** [comment]
So i guess it was an error/misunderstanding on my end... i was making the type = "NEVER" change in the "tramplestopper-common.toml" file, making it in "tramplestopper.json" seems to do the trick.
