### ISSUE TITLE
Latest version crashing on 1.21

### ISSUE THREAD

**Issue by JermsyBoy** [UnRealDinnerbone/TrampleStopper#18]
### Minecraft Version

1.21

### Modloader

fabric-loader-0.16.0-1.21

### Mod version

tramplestopper-fabric-6.0.1+mc1.21

### Latest version?

- [X] Yes

### Repeatable?

- [ ] Yes

### Link to log files

[crash-2024-07-11_14.10.17-client.txt](https://github.com/user-attachments/files/16182476/crash-2024-07-11_14.10.17-client.txt)

### Description of the issue you are having

Unable to launch the game with latest version of mod, both with other mods and on it's own.

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Install Trenzalore https://www.curseforge.com/minecraft/mc-mods/trenzalore/files/5512020/d
