### ISSUE TITLE
[Issue] Server console gets spammed

### ISSUE THREAD

**Issue by TQNL** [UnRealDinnerbone/TrampleStopper#19]
### Minecraft Version

1.21

### Modloader

fabric-0.100.4+1.21

### Mod version

6.0.1+mc1.21

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

I'd rather not, because of privacy

### Steps to reproduce the issue

make a server with the mod installed on fabric

### Description of the issue you are having

the console/log get spammed with `[<time>] [Server thread/INFO]: [STDOUT]: TrampleStopperMixin`

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Sorry I can’t help you less upload your
Logs

**Comment by TQNL** [comment]
[latest.log](https://github.com/user-attachments/files/16183639/latest.log)

I inspected the log file, I think it might be fine privacy wise. As I said, the log is spammed with `[<time>] [Server thread/INFO]: [STDOUT]: TrampleStopperMixin`

**Comment by UnRealDinnerbone** [comment]
7.0.1 should fix it
