### ISSUE TITLE
Crash on startup with version 1.1.1

### ISSUE THREAD

**Issue by angelnc1989** [UnRealDinnerbone/TrampleStopper#2]
https://pastebin.com/7GARC9p2

**Comment by UnRealDinnerbone** [comment]
Alright new version should be on CurseForge soon. The Update really did not add anything it was just a code clean / refactoring 
And Thank you for reporting this bug

**Comment by UnRealDinnerbone** [comment]
Alright new version in live on curseforge https://minecraft.curseforge.com/projects/trample-stopper/files/2615234
