### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by wetsail** [UnRealDinnerbone/TrampleStopper#4]
I just updated to 1.14.4 and started using the 2.0.0.16 version of this mod. 

I started farming potatoes and carrots in a spot likely to get trampled, and villagers immediately trampled half the farm. I tried jumping on the farm myself, and the ground became trampled in three jumps.

The config file has trample set to "Never". I even deleted the config file to be sure, and then changed the new config to "Never" and saved it.

Previous versions of this mod worked fine, but updating to 1.14.4 broke it.

**Comment by UnRealDinnerbone** [comment]
will take a look this weekend

**Comment by bloodconfetti** [comment]
Also would love this mod to be fixed if possible. Do you need any information?

Here's what I have the config file setup, is this incorrect?
`[general]
	#Level of Feather Falling needed
	#Range: 1 ~ 3
	level = 1
	#When should farmland get trampled
	#Never: Never trampled farmland
	#Always: It Always get trampled
	#Default: Normal behavior
	#Feather Falling: Does not get trampled with you have feather falling boots
	type = "Never"`

**Comment by UnRealDinnerbone** [comment]
I been busy sorry

**Comment by UnRealDinnerbone** [comment]
Alright this should fix it https://www.curseforge.com/minecraft/mc-mods/trample-stopper/files/2761717

**Comment by UnRealDinnerbone** [comment]
Please let me know it if does

**Comment by bloodconfetti** [comment]
[Unfortunately I can't test it. My Minecraft is perma broken rn... sorry. Hope someone else can let you know.]
