### ISSUE TITLE
Not working on mc 1.16.2

### ISSUE THREAD

**Issue by alorg** [UnRealDinnerbone/TrampleStopper#7]
Hi I tried various of the downloads and noe load with version 1.16.2 mind fixing it. Thanks

**Comment by UnRealDinnerbone** [comment]
Should be fixed, should be on curseforge soon

**Comment by exful3** [comment]
Still broken for me with the new update, sadly!

**Comment by UnRealDinnerbone** [comment]
New version on curseforge should fix it
